### PR TITLE
Updated app for single APK F-droid build

### PR DESCRIPTION
**Pull request by duggalsu**
- Modified build.gradle to help write an F-droid recipe for single ABI apk output
    - Disabled universal build
    - F-droid currently does not allow multiple gradle APK splits - https://gitlab.com/fdroid/fdroidserver/-/issues/82
- Updated gradle version

### CODE REVIEW

**Comment by ligi** [comment]
Any way we can just make the f-droid flavor a single-apk?

**Comment by duggalsu** [comment]
Yes, I've already written a recipe that can create either flavor.  Can test it only once this PR is merged. I think that it should work and then I just need a project license

**Comment by ligi** [comment]
sorry missed the license here - adding via #10 
wonder why you can only test the "either flavor" when this is merged though

**Comment by duggalsu** [comment]
That's because fdroidserver uses the recipe to pull the repo from github for building. So the repo should have the updated code for testing before I can test and successfully merge in fdroiddata

**Comment by duggalsu** [comment]
Hey @ligi , shall I make any other changes?

**Comment by duggalsu** [comment]
Is there any issue blocking this?

**Comment by ildar** [comment]
Time to tag & release?

**Review by ligi — APPROVED** [review]

**Pull request merged**
